/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mbr.industrymanagement.screens;

import industrymanagement.DataBaseFunctions;
import com.mbr.industrymanagement.db.Product;
import com.mbr.industrymanagement.db.Movimentation;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nsousa
 */
public class InFrame extends javax.swing.JFrame {

    /**
     * Creates new form InFrame
     */
    public InFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGDiscount = new javax.swing.ButtonGroup();
        jPTransaction = new javax.swing.JPanel();
        jLProductName = new javax.swing.JLabel();
        jTProductName = new javax.swing.JTextField();
        jLProductId = new javax.swing.JLabel();
        jTProductId = new javax.swing.JTextField();
        jBSave = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jLProductQuantity = new javax.swing.JLabel();
        jTProductQuantity = new javax.swing.JTextField();
        jCBUnitMeasure = new javax.swing.JComboBox<>();
        jLUnitMeasure = new javax.swing.JLabel();
        jLTotalAmount = new javax.swing.JLabel();
        jTTotalAmount = new javax.swing.JTextField();
        jLDiscount = new javax.swing.JLabel();
        jRBDiscountYes = new javax.swing.JRadioButton();
        jRBDiscountNo = new javax.swing.JRadioButton();
        jTDiscountValue = new javax.swing.JTextField();
        jLInTransaction = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPTransaction.setBackground(new java.awt.Color(0, 0, 0));

        jLProductName.setBackground(new java.awt.Color(255, 0, 0));
        jLProductName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLProductName.setForeground(new java.awt.Color(255, 0, 0));
        jLProductName.setText("Nome do Produto");
        jLProductName.setToolTipText("");

        jTProductName.setBackground(new java.awt.Color(204, 204, 204));
        jTProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTProductNameActionPerformed(evt);
            }
        });

        jLProductId.setBackground(new java.awt.Color(255, 0, 0));
        jLProductId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLProductId.setForeground(new java.awt.Color(255, 0, 0));
        jLProductId.setText("Id do Produto");
        jLProductId.setToolTipText("");

        jTProductId.setBackground(new java.awt.Color(204, 204, 204));

        jBSave.setBackground(new java.awt.Color(255, 0, 0));
        jBSave.setText("Salvar");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jBCancel.setBackground(new java.awt.Color(255, 0, 0));
        jBCancel.setText("Cancelar");
        jBCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCancelMouseClicked(evt);
            }
        });
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        jLProductQuantity.setBackground(new java.awt.Color(255, 0, 0));
        jLProductQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLProductQuantity.setForeground(new java.awt.Color(255, 0, 0));
        jLProductQuantity.setText("Quantidade do Produto");
        jLProductQuantity.setToolTipText("");

        jTProductQuantity.setBackground(new java.awt.Color(204, 204, 204));

        jCBUnitMeasure.setBackground(new java.awt.Color(0, 0, 0));
        jCBUnitMeasure.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCBUnitMeasure.setForeground(new java.awt.Color(255, 0, 0));
        jCBUnitMeasure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogramas", "Litros", "Metros" }));

        jLUnitMeasure.setBackground(new java.awt.Color(255, 0, 0));
        jLUnitMeasure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLUnitMeasure.setForeground(new java.awt.Color(255, 0, 0));
        jLUnitMeasure.setText("Unidade de Medida");
        jLUnitMeasure.setToolTipText("");

        jLTotalAmount.setBackground(new java.awt.Color(255, 0, 0));
        jLTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLTotalAmount.setForeground(new java.awt.Color(255, 0, 0));
        jLTotalAmount.setText("Valor Total");
        jLTotalAmount.setToolTipText("");

        jTTotalAmount.setBackground(new java.awt.Color(204, 204, 204));
        jTTotalAmount.setText("R$");
        jTTotalAmount.setToolTipText("");
        jTTotalAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTTotalAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTTotalAmountFocusLost(evt);
            }
        });
        jTTotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTotalAmountActionPerformed(evt);
            }
        });

        jLDiscount.setBackground(new java.awt.Color(255, 0, 0));
        jLDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLDiscount.setForeground(new java.awt.Color(255, 0, 0));
        jLDiscount.setText("Desconto");
        jLDiscount.setToolTipText("");

        jRBDiscountYes.setBackground(new java.awt.Color(0, 0, 0));
        bGDiscount.add(jRBDiscountYes);
        jRBDiscountYes.setForeground(new java.awt.Color(255, 0, 0));
        jRBDiscountYes.setText("Sim");

        jRBDiscountNo.setBackground(new java.awt.Color(0, 0, 0));
        bGDiscount.add(jRBDiscountNo);
        jRBDiscountNo.setForeground(new java.awt.Color(255, 0, 0));
        jRBDiscountNo.setText("Não");

        jTDiscountValue.setBackground(new java.awt.Color(204, 204, 204));
        jTDiscountValue.setText("R$");
        jTDiscountValue.setToolTipText("- Valor do Desconto em Reais");
        jTDiscountValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTDiscountValueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTDiscountValueFocusLost(evt);
            }
        });
        jTDiscountValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDiscountValueActionPerformed(evt);
            }
        });

        jLInTransaction.setBackground(new java.awt.Color(255, 0, 0));
        jLInTransaction.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLInTransaction.setForeground(new java.awt.Color(255, 0, 0));
        jLInTransaction.setText("Transação de Entrada");

        javax.swing.GroupLayout jPTransactionLayout = new javax.swing.GroupLayout(jPTransaction);
        jPTransaction.setLayout(jPTransactionLayout);
        jPTransactionLayout.setHorizontalGroup(
            jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTransactionLayout.createSequentialGroup()
                .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTransactionLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPTransactionLayout.createSequentialGroup()
                                .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLProductName)
                                    .addComponent(jTProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLProductId)))
                            .addGroup(jPTransactionLayout.createSequentialGroup()
                                .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLTotalAmount)
                                    .addComponent(jLDiscount)
                                    .addGroup(jPTransactionLayout.createSequentialGroup()
                                        .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRBDiscountYes)
                                            .addComponent(jRBDiscountNo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPTransactionLayout.createSequentialGroup()
                                            .addComponent(jTProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCBUnitMeasure, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPTransactionLayout.createSequentialGroup()
                                            .addComponent(jLProductQuantity)
                                            .addGap(25, 25, 25)
                                            .addComponent(jLUnitMeasure))))
                                .addGap(0, 267, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTransactionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTransactionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLInTransaction)
                .addGap(170, 170, 170))
        );
        jPTransactionLayout.setVerticalGroup(
            jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTransactionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLInTransaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPTransactionLayout.createSequentialGroup()
                        .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPTransactionLayout.createSequentialGroup()
                                .addComponent(jLProductId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPTransactionLayout.createSequentialGroup()
                                .addComponent(jLProductName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLProductQuantity)
                            .addComponent(jLUnitMeasure))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBUnitMeasure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTProductQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLTotalAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLDiscount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBDiscountYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBDiscountNo))
                    .addComponent(jTDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTotalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTotalAmountActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jTProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTProductNameActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        // TODO add your handling code here:
        Movimentation movimentation = new Movimentation();
        movimentation.setId(String.valueOf(System.currentTimeMillis()));
        movimentation.setName("Transação de Entrada");
        Product product = new Product();
        product.setId(jTProductId.getText());
        product.setName(jTProductName.getText());
        movimentation.setProduct(product);
        movimentation.setDate(String.valueOf(System.currentTimeMillis()));
        movimentation.setQuantity(Integer.valueOf(jTProductQuantity.getText()));
        movimentation.setAmountValue(new BigDecimal(jTTotalAmount.getText()));
        movimentation.setDiscount(bGDiscount.isSelected(jRBDiscountYes.getModel()));
        movimentation.setDiscountValue(Double.valueOf(jTDiscountValue.getText()));
        movimentation.setUnitOfMeasure(jCBUnitMeasure.getSelectedItem().toString());
        
        try {
            DataBaseFunctions.insertMovimentation(movimentation);
            this.setVisible(false);
            this.dispose();
            MainFrame mainFrame =  new MainFrame();
            mainFrame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(InFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jTTotalAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTTotalAmountFocusGained
        // TODO add your handling code here:
        if(jTTotalAmount.getText().contains("R$"))
        { 
            jTTotalAmount.setText("");
        }
    }//GEN-LAST:event_jTTotalAmountFocusGained

    private void jTTotalAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTTotalAmountFocusLost
        // TODO add your handling code here:
        if(jTTotalAmount.getText().equals(""))
        {
            jTTotalAmount.setText("R$");
        }
    }//GEN-LAST:event_jTTotalAmountFocusLost

    private void jBCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_jBCancelMouseClicked

    private void jTDiscountValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDiscountValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDiscountValueActionPerformed

    private void jTDiscountValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTDiscountValueFocusGained
        // TODO add your handling code here:
        if(jTDiscountValue.getText().contains("R$"))
        { 
            jTDiscountValue.setText("");
        }
    }//GEN-LAST:event_jTDiscountValueFocusGained

    private void jTDiscountValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTDiscountValueFocusLost
        // TODO add your handling code here:
        if(jTDiscountValue.getText().equals(""))
        {
            jTDiscountValue.setText("R$");
        }
    }//GEN-LAST:event_jTDiscountValueFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGDiscount;
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBSave;
    private javax.swing.JComboBox<String> jCBUnitMeasure;
    private javax.swing.JLabel jLDiscount;
    private javax.swing.JLabel jLInTransaction;
    private javax.swing.JLabel jLProductId;
    private javax.swing.JLabel jLProductName;
    private javax.swing.JLabel jLProductQuantity;
    private javax.swing.JLabel jLTotalAmount;
    private javax.swing.JLabel jLUnitMeasure;
    private javax.swing.JPanel jPTransaction;
    private javax.swing.JRadioButton jRBDiscountNo;
    private javax.swing.JRadioButton jRBDiscountYes;
    private javax.swing.JTextField jTDiscountValue;
    private javax.swing.JTextField jTProductId;
    private javax.swing.JTextField jTProductName;
    private javax.swing.JTextField jTProductQuantity;
    private javax.swing.JTextField jTTotalAmount;
    // End of variables declaration//GEN-END:variables
}
