/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mbr.industrymanagement.screens;

import com.mbr.industrymanagement.db.Movimentation;
import com.mbr.industrymanagement.db.Product;
import industrymanagement.DataBaseFunctions;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nsousa
 */
public class OutFrame extends javax.swing.JFrame {

    /**
     * Creates new form OutFrame
     */
    public OutFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLInTransaction = new javax.swing.JLabel();
        jLProductName = new javax.swing.JLabel();
        jLProductId = new javax.swing.JLabel();
        jLProductQuantity = new javax.swing.JLabel();
        jLTotalAmount = new javax.swing.JLabel();
        jTTotalAmount = new javax.swing.JTextField();
        jLDiscount = new javax.swing.JLabel();
        jRBDiscountYes = new javax.swing.JRadioButton();
        jRBDiscountNo = new javax.swing.JRadioButton();
        jTDiscountValue = new javax.swing.JTextField();
        jBCancel = new javax.swing.JButton();
        jBSave = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLInTransaction.setBackground(new java.awt.Color(255, 0, 0));
        jLInTransaction.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLInTransaction.setForeground(new java.awt.Color(255, 0, 0));
        jLInTransaction.setText("Transação de Saída");

        jLProductName.setBackground(new java.awt.Color(255, 0, 0));
        jLProductName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLProductName.setForeground(new java.awt.Color(255, 0, 0));
        jLProductName.setText("Nome do Produto");
        jLProductName.setToolTipText("");

        jLProductId.setBackground(new java.awt.Color(255, 0, 0));
        jLProductId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLProductId.setForeground(new java.awt.Color(255, 0, 0));
        jLProductId.setText("Id do Produto");
        jLProductId.setToolTipText("");

        jLProductQuantity.setBackground(new java.awt.Color(255, 0, 0));
        jLProductQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLProductQuantity.setForeground(new java.awt.Color(255, 0, 0));
        jLProductQuantity.setText("Quantidade do Produto");
        jLProductQuantity.setToolTipText("");

        jLTotalAmount.setBackground(new java.awt.Color(255, 0, 0));
        jLTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLTotalAmount.setForeground(new java.awt.Color(255, 0, 0));
        jLTotalAmount.setText("Valor Total");
        jLTotalAmount.setToolTipText("");

        jTTotalAmount.setBackground(new java.awt.Color(204, 204, 204));
        jTTotalAmount.setText("R$");
        jTTotalAmount.setToolTipText("");
        jTTotalAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTTotalAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTTotalAmountFocusLost(evt);
            }
        });
        jTTotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTotalAmountActionPerformed(evt);
            }
        });

        jLDiscount.setBackground(new java.awt.Color(255, 0, 0));
        jLDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLDiscount.setForeground(new java.awt.Color(255, 0, 0));
        jLDiscount.setText("Desconto");
        jLDiscount.setToolTipText("");

        jRBDiscountYes.setBackground(new java.awt.Color(0, 0, 0));
        jRBDiscountYes.setForeground(new java.awt.Color(255, 0, 0));
        jRBDiscountYes.setText("Sim");

        jRBDiscountNo.setBackground(new java.awt.Color(0, 0, 0));
        jRBDiscountNo.setForeground(new java.awt.Color(255, 0, 0));
        jRBDiscountNo.setText("Não");

        jTDiscountValue.setBackground(new java.awt.Color(204, 204, 204));
        jTDiscountValue.setText("R$");
        jTDiscountValue.setToolTipText("- Valor do Desconto em Reais");
        jTDiscountValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTDiscountValueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTDiscountValueFocusLost(evt);
            }
        });
        jTDiscountValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDiscountValueActionPerformed(evt);
            }
        });

        jBCancel.setBackground(new java.awt.Color(255, 0, 0));
        jBCancel.setText("Cancelar");
        jBCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCancelMouseClicked(evt);
            }
        });
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        jBSave.setBackground(new java.awt.Color(255, 0, 0));
        jBSave.setText("Salvar");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(jTextPane1);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(185, 185, 185)
                            .addComponent(jLInTransaction)
                            .addGap(160, 160, 160))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLProductName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLProductId))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLTotalAmount)
                                            .addComponent(jLDiscount)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRBDiscountYes)
                                                    .addComponent(jRBDiscountNo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLProductQuantity))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(19, 19, 19)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLInTransaction)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLProductId)
                                .addComponent(jLProductName))
                            .addGap(35, 35, 35)
                            .addComponent(jLProductQuantity)
                            .addGap(41, 41, 41)
                            .addComponent(jLTotalAmount)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLDiscount)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRBDiscountYes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRBDiscountNo))
                        .addComponent(jTDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTTotalAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTTotalAmountFocusGained
        // TODO add your handling code here:
        if(jTTotalAmount.getText().contains("R$"))
        {
            jTTotalAmount.setText("");
        }
    }//GEN-LAST:event_jTTotalAmountFocusGained

    private void jTTotalAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTTotalAmountFocusLost
        // TODO add your handling code here:
        if(jTTotalAmount.getText().equals(""))
        {
            jTTotalAmount.setText("R$");
        }
    }//GEN-LAST:event_jTTotalAmountFocusLost

    private void jTTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTotalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTotalAmountActionPerformed

    private void jTDiscountValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTDiscountValueFocusGained
        // TODO add your handling code here:
        if(jTDiscountValue.getText().contains("R$"))
        {
            jTDiscountValue.setText("");
        }
    }//GEN-LAST:event_jTDiscountValueFocusGained

    private void jTDiscountValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTDiscountValueFocusLost
        // TODO add your handling code here:
        if(jTDiscountValue.getText().equals(""))
        {
            jTDiscountValue.setText("R$");
        }
    }//GEN-LAST:event_jTDiscountValueFocusLost

    private void jTDiscountValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDiscountValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDiscountValueActionPerformed

    private void jBCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_jBCancelMouseClicked

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        // TODO add your handling code here:
        Movimentation movimentation = new Movimentation();
        movimentation.setId(String.valueOf(System.currentTimeMillis()));
        movimentation.setName("Transação de Saída");
        Product product = new Product();
//        product.setId(jTProductId.getText());
//        product.setName(jTProductName.getText());
        movimentation.setProduct(product);
        movimentation.setDate(String.valueOf(System.currentTimeMillis()));
//        movimentation.setQuantity(Integer.valueOf(jTProductQuantity.getText()));
//        movimentation.setAmountValue(new BigDecimal(jTTotalAmount.getText()));
//        movimentation.setDiscount(bGDiscount.isSelected(jRBDiscountYes.getModel()));
        movimentation.setDiscountValue(Double.valueOf(jTDiscountValue.getText()));
//        movimentation.setUnitOfMeasure(jCBUnitMeasure.getSelectedItem().toString());

        try {
            DataBaseFunctions.insertMovimentation(movimentation);
            this.setVisible(false);
            this.dispose();
            MainFrame mainFrame =  new MainFrame();
            mainFrame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(InFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBSave;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLDiscount;
    private javax.swing.JLabel jLInTransaction;
    private javax.swing.JLabel jLProductId;
    private javax.swing.JLabel jLProductName;
    private javax.swing.JLabel jLProductQuantity;
    private javax.swing.JLabel jLTotalAmount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBDiscountNo;
    private javax.swing.JRadioButton jRBDiscountYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDiscountValue;
    private javax.swing.JTextField jTTotalAmount;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
